ignore:
  - "pkg/api/**"
  - "**/*_generated.go"
  - "**/mocks/**"
coverage:
  status:
    project:
      default:
        target: 90%
        threshold: 3%
    patch:
      default:
        target: 85%
        threshold: 5%
